update Dockerfile to add support for openshift dynamic UID constraints
anchore/anchore-engine pull request #587
Opened 2020-08-21 23:35 UTC by nurmi

Fixes #586.

Signed-off-by: Daniel Nurmi <nurmi@anchore.com>

2020-10-01 22:52 UTC, Btodhunter requested changes

2020-10-01 22:52 UTC, Btodhunter commented on Dockerfile
> +    chown -R 1000:0 /workspace_preload /var/log/anchore /var/run/anchore /analysis_scratch /workspace /anchore_service ${ANCHORE_SERVICE_DIR} /home/anchore/clamav && \
I think we want to chown & chmod g+ the entire /home/anchore directory here. Our chart mounts certs & the license.yaml to /home/anchore/certs and it'll get mounted with the same owners as the parent directory.

2020-10-02 23:40 UTC, Btodhunter approved these changes

2020-10-09 00:46 UTC, zhill commented
Closing this as it is in 0.8.2-dev and will merge in with that branch.

2020-10-09 00:46 UTC, closed without merging