Add capabilities for passing in clamscan arguments
anchore/anchore-engine pull request #625
Opened 2020-09-17 18:37 UTC by dakaneye

Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

**What this PR does / why we need it**: We need to make the clamscan command more configurable in case people need to process images larger than 25mb. 

**Which issue this PR fixes**: fixes #615

**Special notes**:

2020-09-17 18:38 UTC, dakaneye commented on anchore_engine/analyzers/malware.py
> +        self.cmdline_args = self.config.get(self.name, {}).get('cmdline_args', [])
this could be renamed if anyone thinks of a better name! Maybe **clamscan_args**

2020-09-17 20:59 UTC, dakaneye commented
Also noting that this needs to get updated to point to the release branch when it's created.

2020-09-22 17:40 UTC, dakaneye commented
@zhill this is pointing to the 0.8.2-dev branch now, so should be ready for review.

2020-10-01 19:03 UTC, zhill requested changes
This allows the setting of parameters, but I don't see a new default for the size limits. I think a size limit of something like 10Gb (default docker image max size) is necessary to ensure the scans take place if configured and admins can tune it down.

If the image squashed.tar is larger than the setting value, the analyzer should log an error and skip the scan to ensure the results aren't incorrect.

2020-10-01 23:07 UTC, dakaneye commented on anchore_engine/analyzers/malware.py
> +def append_cmdline_args(cmd: str, cmdline_args: list):
added!

2020-10-02 21:48 UTC, zhill commented
@dakaneye Was this based on master? I think it needs to be rebased onto v0.8.2-dev as it looks like its pulling in a bunch of other commits that aren't part of this fix.

2020-10-05 15:47 UTC, zhill requested changes
Default seems to differ from our discussion, but otherwise looks good.

2020-10-05 15:47 UTC, zhill commented on anchore_engine/analyzers/malware.py
> +CLAMAV_CMD = "clamscan --suppress-ok-results --infected --recursive --allmatch --archive-verbose --tempdir={tempdir} --database={database} --max-filesize=1000m --max-scansize=1000m"
We discussed 10GB max, but this is 1GB.

2020-10-05 16:34 UTC, dakaneye commented on anchore_engine/analyzers/malware.py
> +CLAMAV_CMD = "clamscan --suppress-ok-results --infected --recursive --allmatch --archive-verbose --tempdir={tempdir} --database={database} --max-filesize=1000m --max-scansize=1000m"
my mistake! Fixed to 4gb as discussed

2020-10-05 23:49 UTC, merged