Rpm handler syft package.
anchore/anchore-engine pull request #701
Opened 2020-11-05 19:08 UTC by Toure

**What this PR does / why we need it**:
Created a rpm handler for anchore-engine to interface with syft, this will replace a portion of the current 10_packages_list module with a call into syft.   https://github.com/anchore/anchore-engine/issues/682

2020-11-05 19:17 UTC, alfredodeza requested changes

2020-11-05 19:17 UTC, alfredodeza commented on anchore_engine/analyzers/syft/handlers/rpm.py
> +    # _all_package_files(findings, artifact)
looks like this needs to get removed?

2020-11-05 19:17 UTC, alfredodeza commented on tests/functional/clients/standalone/package_list/test_centos.py
> +        # import ipdb; ipdb.set_trace()
this needs to get removed

2020-11-05 19:17 UTC, alfredodeza commented on tests/functional/clients/standalone/package_list/test_centos.py
> +    # @pytest.mark.parametrize('path', path_params(centos.pkgfiles_all))
are you meant to comment this out? or was this temporary only?

2020-11-05 19:19 UTC, Toure commented on tests/functional/clients/standalone/package_list/test_centos.py
> +        # import ipdb; ipdb.set_trace()
Thanks for catching that.

2020-11-05 20:02 UTC, wagoodman commented on tests/functional/clients/standalone/package_list/test_centos.py
> +        loaded = pkgs.get(pkg, '{}')
`'{}'` --> `{}`

2020-11-09 21:57 UTC, alfredodeza commented on tests/functional/clients/standalone/package_list/test_centos.py
> +    # @pytest.mark.parametrize('path', path_params(centos.pkgfiles_all))
why can't this be kept uncommented bith with a `skipif` ? The TODO message could be the `skipif` reason

2020-11-10 00:31 UTC, Toure reviewed
Added the skip decorator to the test.

2020-11-10 12:07 UTC, alfredodeza approved these changes

2020-11-10 16:50 UTC, merged