feat: ability to exclude packages by their path
anchore/anchore-engine pull request #751
Opened 2020-12-01 22:27 UTC by ssthom

Signed-off-by: Shawn Thompson <ssthomps@us.ibm.com>

**What this PR does / why we need it**:

Adds the ability for users to exclude packages in the policy bundle based on the package path

```
{
  "name": "package_path_exclude",
  "value": ".*newrelic.*"
}
```

**Which issue this PR fixes** 

fixes #: https://github.com/anchore/anchore-engine/issues/229

**Special notes**:

2020-12-02 01:11 UTC, zhill commented
Hi @ssthom thanks for this! We'll give it a look. The approach makes sense.

2020-12-09 20:18 UTC, dakaneye requested changes
@ssthom Great job submitting this change! Looks like you did things in a consistent manner across the board, and the logic seems sound.

My debug log comment is optional, however I'd like to request the addition of a unit test for the package exclusion as part of this change. Thanks!

2020-12-09 20:18 UTC, dakaneye commented on anchore_engine/services/policy_engine/engine/policy/gates/vulnerabilities.py
> +                                        continue
I would consider adding at least a debug log here. When a package gets excluded by a path it might be helpful for troubleshooting later on.

2020-12-09 20:53 UTC, ssthom commented
@dakaneye Added debug statement, but I'm new to the repo could you point me to an existing test to use as a basis or in the right direction. I didn't see any vulnerability gate tests in https://github.com/anchore/anchore-engine/tree/master/tests/unit/anchore_engine/services/policy_engine/policy/gates

2020-12-09 21:18 UTC, dakaneye commented
> @dakaneye Added debug statement, but I'm new to the repo could you point me to an existing test to use as a basis or in the right direction. I didn't see any vulnerability gate tests in https://github.com/anchore/anchore-engine/tree/master/tests/unit/anchore_engine/services/policy_engine/policy/gates

@ssthom , I saw some [here](https://github.com/anchore/anchore-engine/blob/master/tests/integration/services/policy_engine/engine/policy/gates/test_vulnerabilities.py), sorry looks like they're actually integration tests, my bad

2020-12-15 21:18 UTC, zhill commented
Ack, we'll review tests as we add unit tests for this as part of unit test coverage for the gate overall.

2020-12-15 21:18 UTC, merged