Use MB for max image size config instead of bytes
anchore/anchore-engine pull request #841
Opened 2021-01-13 19:42 UTC by zburstein

I originally built the configuration value to be stored in bytes but MB makes more sense from a user perspective. Logging still shows values in bytes for granularity

Signed-off-by: Zane Burstein <zane.burstein@anchore.com>

2021-01-15 05:42 UTC, zhill requested changes
Looks good just please add the _mb or _MB suffix to the configs so its clear to users that they should specify megabytes instead of bytes in this value.

2021-01-15 05:42 UTC, zhill commented on Dockerfile
> +    ANCHORE_MAX_COMPRESSED_IMAGE_SIZE=-1
Please add the unit here since it's not bytes, ANCHORE_MAX_COMPRESSED_IMAGE_SIZE_MB, will work. Just to be clear on units in the name.

2021-01-15 05:42 UTC, zhill commented on anchore_engine/configuration/localconfig.py
> +    "max_compressed_image_size": -1,
Also, here if we can add unit since it isn't bytes: max_compressed_image_size_mb

2021-01-15 22:46 UTC, dakaneye approved these changes
LGTM

2021-01-16 00:02 UTC, zhill approved these changes
lgtm

2021-01-16 01:15 UTC, merged