Remove CPE hashing
anchore/anchore-engine pull request #957
Opened 2021-03-26 22:44 UTC by dakaneye

(it is a remnant of inaccurate de-dup logic from before the improvements added in 3.0)

Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

2021-03-26 22:49 UTC, nightfurys approved these changes
lgtm. Yay for losing redundant dedups!

2021-03-26 23:36 UTC, dakaneye commented
All of the removed string methods were not used (I did a string search for those method names). It seemed that only the method from ImageCpe was actually used, and I ported that over to be a static method in the common/helpers.py file with some unit tests. LMK what you think.

2021-03-30 21:03 UTC, nightfurys requested changes
Refactored methods are not all the same. There are subtle differences between the functions in ImageCpe and CpeV2Vulnerability/VulnDBCpe

2021-03-30 21:07 UTC, nightfurys commented
> All of the removed string methods were not used (I did a string search for those method names). It seemed that only the method from ImageCpe was actually used, and I ported that over to be a static method in the common/helpers.py file with some unit tests. LMK what you think.

get_cpe23string function in CpeV2Vulnerability/VulnDBCpe is used
https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/policy_engine/api/controllers/synchronous_operations.py#L1008

2021-03-31 01:01 UTC, nightfurys approved these changes

2021-03-31 16:23 UTC, merged